import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import { Providers } from "./providers";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

const gangwonEduAll = localFont({
  src: [
    {
      path: "../../public/fonts/GangwonEduAllBold.ttf",
      weight: "700",
    },
    {
      path: "../../public/fonts/GangwonEduAllLight.ttf",
      weight: "300",
    },
  ],
  display: "swap",
  variable: "--font-gangwonEduAll",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={`${pretendard.variable} ${gangwonEduAll.variable}`}>
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
